### ISSUE TITLE
Using Open Street Map Provider instead of Google Maps.

### ISSUE THREAD

**Issue by israteneda** [CUTR-at-USF/OpenTripPlanner-for-Android#492]
Hello! 
I am a beginner with OTP Android. I checked that the application uses google maps. I would like to know if Google charges me money for the use of the API. And if I can use Open Street Maps instead of Google maps. Regards.

**Comment by barbeau** [comment]
@israteneda As of right now Google doesn't charge for using the Android Maps SDK:
https://developers.google.com/maps/documentation/android-sdk/intro

You could port to another Maps SDK provider such as MapBox SDK or OSMDroid instead of Google Maps, but to my knowledge as of right now there aren't any other SDKs that have exact API parity with Android Maps SDK (v2), so it would require some software changes.

Note that you can still use OSM map tiles with the Android Maps SDK, and OTP Android supports that currently.

**Comment by israteneda** [comment]
Thank you for your answer @barbeau. Can you provide me more information about "use OSM map tiles with the Android Maps SDK", please?
Regards.

**Comment by barbeau** [comment]
@israteneda See:
* Google docs - https://developers.google.com/maps/documentation/android-sdk/tileoverlay
* OTP Android code - https://github.com/CUTR-at-USF/OpenTripPlanner-for-Android/blob/master/opentripplanner-android/src/main/java/edu/usf/cutr/opentripplanner/android/fragments/MainFragment.java#L3558
